---

- name: Install Apache with page
  hosts: linux_servers
  become: yes

  vars:
          source_folder: ./testweb3
          destin_folder: /var/www/html
  tasks:
  - name: Check Linux Distr
    debug: var=ansible_os_family

  - block:  # Rhel Block 


        - name: Install Apache for Rhel
          yum: name=httpd state=installed

        - name: Start Apache Rhel
          command: /usr/sbin/httpd
    when: ansible_os_family == "RedHat"


  - block:    # Ubuntu Block
        - name: Install Apache for ubuntu
          apt: name=apache2 state=latest

        - name: Start Apache Ubuntu
          command: /usr/sbin/apachectl start
    when: ansible_os_family == "Debian"

  - name: Generate HTML
    template: src={{ source_folder }}/index.j2 dest={{ destin_folder }}/index.html mode=0555
    notify:
      - Restart Apache Rhel
      - Restart Apache Ubuntu

  - name: Copy Web
    copy: src={{ source_folder }}/{{item}} dest={{ destin_folder }} mode=0555
    loop:
      - "google.png"
      - "centos.png"
    notify: 
      - Restart Apache Rhel
      - Restart Apache Ubuntu

  handlers:
  - name: Restart Apache Rhel
    shell: pkill httpd; /usr/sbin/httpd
    when: ansible_os_family == "RedHat"

  - name: Restart Apache Ubuntu
    shell: /usr/sbin/apachectl restart
    when: ansible_os_family == "Debian"

