---

- name: Install Apache with page
  hosts: linux_servers
  become: yes

  vars:
          source_file: ./testweb/index.html
          destin_file: /var/www/html
  tasks:
  - name: Check Linux Distr
    debug: var=ansible_os_family

  - name: Install Apache for Rhel
    yum: name=httpd state=installed
    when: ansible_os_family == "RedHat"

  - name: Install Apache for ubuntu
    apt: name=apache2 state=latest
    when: ansible_os_family == "Debian"

  - name: Copy Web
    copy: src={{ source_file }} dest={{ destin_file }} mode=0555
    notify: Restart Apache 

  - name: Start Apache Rhel
    command: /usr/sbin/httpd
    when: ansible_os_family == "RedHat"

  - name: Start Apache Ubuntu
    command: /usr/sbin/apachectl start
    when: ansible_os_family == "Debian"

  handlers:
  - name: Restart Apache Rhel
    shell: pkill httpd; /usr/sbin/httpd 
  - name: Restart Apache Ubuntu
    shell: pkill apache2; /usr/sbin/apachectl start

