---
# handlers file for deploy_apache
- name: Restart Apache Rhel
  shell: pkill httpd; /usr/sbin/httpd
  when: ansible_os_family == "RedHat"

- name: Restart Apache Ubuntu
  shell: /usr/sbin/apachectl restart
  when: ansible_os_family == "Debian"